import {
  ArrowLeft,
  ArrowRight,
  MoveRight,
  Target,
  Lightbulb,
  TrendingUp,
  Heart,
  CheckCircle2,
  Check,
  Home,
  X,
  Menu,
  ChevronDown,
  HandHeart,
  Users,
  Handshake,
  MapPin,
  Phone,
  Mail,
  Send,
  Globe,
  BadgeCheck,
  ReceiptText,
  Loader2,
  Utensils,
  GraduationCap,
  UserRound,
  Stethoscope,
  PawPrint,
  Leaf,
  Siren,
  FileText,
  Building2,
  Share2,
  Soup,
  BookOpen,
  HeartPulse,
  Star,
} from "lucide-react";

const MAP = {
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right_alt: MoveRight,
  track_changes: Target,
  lightbulb: Lightbulb,
  trending_up: TrendingUp,
  favorite: Heart,
  check_circle: CheckCircle2,
  check: Check,
  home: Home,
  close: X,
  menu: Menu,
  expand_more: ChevronDown,
  volunteer_activism: HandHeart,
  diversity_1: Users,
  handshake: Handshake,
  location_on: MapPin,
  call: Phone,
  mail: Mail,
  send: Send,
  public: Globe,
  verified: BadgeCheck,
  receipt_long: ReceiptText,
  progress_activity: Loader2,
  restaurant: Utensils,
  school: GraduationCap,
  female: UserRound,
  medical_services: Stethoscope,
  pets: PawPrint,
  eco: Leaf,
  emergency: Siren,
  description: FileText,
  business: Building2,
  share: Share2,
  "fa-bowl-food": Soup,
  "fa-book-open": BookOpen,
  "fa-female": UserRound,
  "fa-heart-pulse": HeartPulse,
  "fa-paw": PawPrint,
  "fa-leaf": Leaf,
};

export default function Icon({ name, className = "", ...rest }) {
  const Cmp = MAP[name] || Star;
  return <Cmp className={className} size="1em" aria-hidden="true" {...rest} />;
}
